### ISSUE TITLE
Fix Prometheus OutOfOrderTimestamps

### ISSUE THREAD

**Issue by tirkesi** [FuelLabs/infrastructure#112]
The main issue is it seems prometheus expects the timestamps in a strictly increasing order. If the metrics come in out of order then it drops them and trigger the warning we're getting (PrometheusOutOfOrderTimestamps).

The scrape manager component of Prometheus is reporting errors for two targets (sentry-1-service-monitor and sentry-3-service-monitor), I couldn't find any other targets in the logs.

**Comment by rfuelsh** [comment]
not needed
