### ISSUE TITLE
Upgrade to grafana v10

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/infrastructure#130]
- upgrade fuel-dev to grafana 10
- https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-0/#phlare-renamed-to-grafana-pyroscope

**Comment by rfuelsh** [comment]
![Image](https://github.com/FuelLabs/infrastructure/assets/96140895/b22e46dd-d5b4-4d98-b79c-18935dacbdf1)

Was able to setup pyroscope/phlare and see metrics and traces - see profiling for fuel-core- we will push to automate this with fuel infra v2
