### ISSUE TITLE
Investigate Elasticsearch on elastic.co

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/infrastructure#139]

**Comment by Voxelot** [comment]
brandon to create the trial account

**Comment by rfuelsh** [comment]
We have logs from fuel-k8s-operator in bosshog cluster in elastic co- i will do a demo

the creds for elastic co are in fuel-deployment

**Comment by rfuelsh** [comment]
https://cloud.elastic.co/pricing?elektra=pricing-page

- - Picking "Storage Optimized" - Good for most ingestion use cases with 7-10 days of data available for fast access. Also good for light search use cases without heavy indexing or CPU needs.

- For ElasticSearch Picking 2 AZs for Hot Data and Content Tier " Nodes in this tier ingest and process frequently queried data.":
900 GB storage
30 GB RAM
4 vCPU

Disregard warm and cold data tier - we can archive our logs to S3 through S3-Elastic Connector

- For Kibana, Picking 2 AZs: 
2 GB RAM
Up to 16.8 vCPU

- 2 x Integration Servers
2 GB RAM
Up to 16.8 vCPU

- 1 x enterprise search 
2 GB RAM
Up to 8.4 vCPU

Hourly rate becomes $1.7460
Monthly total becomes $1173.31 dollars

Compare this to Our current elasticsearch it

**Comment by rfuelsh** [comment]
cutting AWS costs 
- cut down cloudwatch, lambda (talk to other support reps)
