### ISSUE TITLE
implement container image audit solutions

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/infrastructure#149]
scan for vulns during docker image building, and skip publishing to ghcr/ecr if there are any open issues / vulns

**Comment by rfuelsh** [comment]
Few options we have

 https://github.com/marketplace/actions/container-scan

https://github.com/marketplace/actions/anchore-container-scan

https://github.com/aquasecurity/trivy

https://github.com/quay/clair

https://github.com/anchore/grype

**Comment by Voxelot** [comment]
@tirkesi says grype is good

**Comment by Voxelot** [comment]
we should test out some of these solutions on a repo

**Comment by rfuelsh** [comment]
https://github.com/FuelLabs/fuel-core/pull/1637

**Comment by rfuelsh** [comment]
ticket for new SRE engineer

**Comment by Voxelot** [comment]
closing ticket as this repo will be archived
