### ISSUE TITLE
Review Latacora Audit Results

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/infrastructure#161]
Review the Latacora Audit Results

**Comment by liviudm** [comment]
where can I find the report/results?

**Comment by rfuelsh** [comment]
@liviudm - sorry forgot to see this- https://drive.google.com/drive/folders/1WN1wKjVOkU0Zc4c9PWK6tjBYONGAUy8k- we will go this in the New Year cc @tirkesi @Voxelot @xgreenx
