### ISSUE TITLE
Setup Basic Telemetry (Prometheus support)

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/infrastructure#28]
We use tracing as per our [coding standard](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/logging.md). However, we need to be able to monitor metrics using systems like prometheus and jaeger. 

Investigate how we'd integrate our tracing infrastructure into telemetry using tools like [tracing-opentelemtry](https://crates.io/crates/tracing-opentelemetry) and setup minimum viable telemetry for fuel-core.

Goals:

- Export rust application metrics to prometheus, could be done using either
   - Scrapeable endpoint on the service, along with auto-discovery configurations in k8s. This would likely use [prometheus_hyper](https://docs.rs/prometheus-hyper/latest/prometheus_hyper/) to integrate with our axum web framework.
   - Direct pushing from the fuel-core node to prometheus using the prometheus push gateway: https://github.com/tikv/rust-prometheus/blob/master/examples/example_push.rs
- Examples and/or framework for iteracting with metrics throughout fuel-core. This may leverage features such as [prometheus_static_metric](https://docs.rs/prometheus-static-metric/latest/prometheus_static_metric/). 
- [stretch goal] Integrate traces from fuel core to work with [Graphana Tracing](https://grafana.com/docs/grafana/latest/explore/trace-integration/), this may involve configuring support for jaeger in addition to prometheus.

Related Tasks:

- [x] FuelLabs/infrastructure#22
- [x] FuelLabs/infrastructure#21
- [ ] FuelLabs/infrastructure#20
- [x] FuelLabs/infrastructure#19
- [x] https://github.com/FuelLabs/fuel-core/issues/249
- [ ] https://github.com/FuelLabs/fuel-core/issues/251
- [ ] https://github.com/FuelLabs/fuel-core/issues/252
- [x] Add Grafana
- [x] Get Grafana to scrape Prometheus
- [ ] add jaeger to fuel-core monitoring deployment scripts
- [ ] macro framework for metrics

**Comment by rfuelsh** [comment]
https://node-beta-1.fuel.network/metrics - @uberscott
