### ISSUE TITLE
Infrastructure Repo automation enhancements

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/infrastructure#69]
Cleanup the infrastructure repo with ansible or comparable solutions to make cluster setup automation idempotent and more maintainable.

1) Improve create-k8s.sh script: https://github.com/FuelLabs/infrastructure/blob/master/scripts/create-k8s.sh 

There is alot of stuff that goes in here and its one big script- we need a better way to deploy it

2) @BossHog1313 once you have updated that script - consult @rfuelsh and then we will discuss how to test deploy your changes via our CI/CD in a session.

**Comment by BossHog1313** [comment]
Will do. Thanks!

**Comment by BossHog1313** [comment]
Looking at this now.

**Comment by BossHog1313** [comment]
I've refactored the create-k8s.sh script and improved usage and error handling. Almost ready to test.

**Comment by BossHog1313** [comment]
@rfuelsh : Ready for testing.

**Comment by BossHog1313** [comment]
Testing deployments with the new _create_k8s_ script now, using our github workflow on a custom kubernetes cluster. Right now, the script is failing during _terraform init_ with "Error: Invalid AWS Region". But I'm almost there.

Thanks much to @rfuelsh for his help getting my test environment established!

**Comment by BossHog1313** [comment]
Fixed the "invalid region" issue. Now working around VPC quota limit.

**Comment by BossHog1313** [comment]
Need a new keypair for us-east-2, then we should be done.

**Comment by BossHog1313** [comment]
Tested. Works beautifully.

**Comment by rfuelsh** [comment]
ready for PR

**Comment by BossHog1313** [comment]
Merged.
