### ISSUE TITLE
Integrate FluxCD into fuel-k8s-operator

### ISSUE THREAD

**Issue by tirkesi** [FuelLabs/infrastructure#84]
- [x] Create resources for Flux controllers
   - image-reflector-controller 
   - image-automation-controller
   - helm-controller
   - kustomize-controller
   - source-controller
   - kubernetes-controllers
- [x] Make fuel-core auto update with image reflector and image automation
   - triggering updates to container images when new versions are available
- [x] Use k8s `role` & `rolebinding` for granting permissions to Flux
   - Clear separation between Flux resources and application resources.
- [x] Fuel-core crd syncs with application on cluster
- [x] Fuel-k8s-operator helm deployment auto updates with fuel-k8s-operator-system on new helmrelease

- run [fuel-core-e2e-client](https://github.com/FuelLabs/fuel-core/tree/master/bin/e2e-test-client) against CD environment after every deployment (this might be tricky with flux)

**Comment by Voxelot** [comment]
waiting on CI/CD

**Comment by liviudm** [comment]
The notifications controller is worth looking into as well. We can configure it to send alerts to Slack when something happens https://fluxcd.io/flux/components/notification/

**Comment by Voxelot** [comment]
blocked on terraform rework #131

**Comment by rfuelsh** [comment]
closing this out
