### ISSUE TITLE
K8s readiness probe to wait for sentries to sync before routing traffic to new sentries

### ISSUE THREAD

**Issue by tirkesi** [FuelLabs/infrastructure#96]

**Comment by rfuelsh** [comment]
@tirkesi - we discussed this extensively amongst ourselves with Green and also with AWS- this maybe not the best approach- but its. a good idea cc @Voxelot - i creaated another ticket #101 to handle this

**Comment by tirkesi** [comment]
@rfuelsh - agreed. liveness and readiness probes can't help us in this situation. we need to find a different solution.
