### ISSUE TITLE
Collect nginx controller metrics in prometheus

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/infrastructure#99]
Enable nginx metrics and collect them in prometheus. This may require changes to the nginx installation script.

https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/

**Comment by rfuelsh** [comment]
- for fuel-deployment-v2: https://github.com/FuelLabs/fuel-deployment-v2/pull/43

- for DEV and PROD- manually deploying - in progress

**Comment by rfuelsh** [comment]
replicated to DEV & PROD - got nginx metrics
